### ISSUE TITLE
'organization_themes' ModuleNotFoundError after installation and startup

### ISSUE THREAD

**Issue by raphaelyancey** [Ircam-Web/Mezzo#1]
After setting up the installation as explained in the README (`git clone` + `docker-compose up`), I'm getting Python errors from `app_1`.

```
app_1    | Traceback (most recent call last):
app_1    |   File "/srv/app/manage.py", line 29, in <module>
app_1    |     execute_from_command_line(sys.argv)
app_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
app_1    |     utility.execute()
app_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 327, in execute
app_1    |     django.setup()
app_1    |   File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 18, in setup
app_1    |     apps.populate(settings.INSTALLED_APPS)
app_1    |   File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
app_1    |     app_config = AppConfig.create(entry)
app_1    |   File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 116, in create
app_1    |     mod = import_module(mod_path)
app_1    |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
app_1    |     return _bootstrap._gcd_import(name[level:], package, level)
app_1    |   File "<frozen importlib._bootstrap>", line 978, in _gcd_import
app_1    |   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
app_1    |   File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
app_1    | ModuleNotFoundError: No module named 'organization_themes'
```

It's prompted several times, and the server isn't accessible and returns a HTTP 500 Internal Server Error on port 8022 (as displayed by `docker ps` instead of 8021 as mentionned in the README) — don't know if it's the cause or not ?

**Comment by yomguy** [comment]
hi @raphaelyancey 
OK I have to check the module setup script...

**Comment by raphaelyancey** [comment]
A `git checkout master` in each `lib/` subdirectory (therefore in `lib/mezzanine-organization-themes`) seems to have fixed the issue.

**Comment by yomguy** [comment]
OK, I'm fixing all the submodule stuff.. ;)
