### ISSUE TITLE
ModuleNotFoundError: No module named 'organization'

### ISSUE THREAD

**Issue by raphaelyancey** [Ircam-Web/Mezzo#2]
At startup:
```
app_1    | Traceback (most recent call last):
app_1    |   File "/srv/app/manage.py", line 29, in <module>
app_1    |     execute_from_command_line(sys.argv)
app_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
app_1    |     utility.execute()
app_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 327, in execute
app_1    |     django.setup()
app_1    |   File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 18, in setup
app_1    |     apps.populate(settings.INSTALLED_APPS)
app_1    |   File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
app_1    |     app_config = AppConfig.create(entry)
app_1    |   File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 116, in create
app_1    |     mod = import_module(mod_path)
app_1    |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
app_1    |     return _bootstrap._gcd_import(name[level:], package, level)
app_1    |   File "<frozen importlib._bootstrap>", line 978, in _gcd_import
app_1    |   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
app_1    |   File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
app_1    | ModuleNotFoundError: No module named 'organization'
```

Going into the app container in `/srv/lib/mezzanine-organization/app/organization`, launching `ipython` and typing `import organization` displays the same error, even if there is a `__init__.py` in the directory.

Still learning Python though :)

**Comment by raphaelyancey** [comment]
Additional informations: 
```
In [1]: import sys

In [2]: print(sys.path)
['', '/usr/local/bin', '/usr/local/lib/python36.zip', '/usr/local/lib/python3.6', '/usr/local/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/site-packages', '/srv/lib/grappelli-safe', '/srv/lib/mezzanine', '/srv/lib/cartridge', '/srv/lib/mezzanine-agenda', '/srv/lib/mezzanine-organization', '/srv/lib/mezzanine-organization-themes', '/usr/local/lib/python3.6/site-packages/IPython/extensions', '/root/.ipython']
```

Seems ok to me so far... `/srv/lib/mezzanine-organization` is in the modules path and `/srv/lib/mezzanine-organization/app/organization` has a `__init__.py`.
